// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateEntry(arg1:string):Promise<boolean>;

export function DeleteEntry(arg1:number):Promise<boolean>;

export function Greet(arg1:string):Promise<string>;

export function ReadData():Promise<Array<main.Todo>>;

export function UpdateEntry(arg1:number,arg2:string,arg3:number):Promise<boolean>;
