// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateEntry(arg1) {
  return window['go']['main']['App']['CreateEntry'](arg1);
}

export function DeleteEntry(arg1) {
  return window['go']['main']['App']['DeleteEntry'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ReadData() {
  return window['go']['main']['App']['ReadData']();
}

export function UpdateEntry(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateEntry'](arg1, arg2, arg3);
}
